# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Mathematical Statistics with a View Toward Machine Learning
author: John Myers
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinx_togglebutton
  config:
    mathjax_config:
      tex:
        macros:
          "argmax": "\\operatorname*{argmax}"
          "argmin": "\\operatorname*{argmin}"
          "MSE": "\\operatorname*{MSE}"
          "MAE": "\\operatorname*{MAE}"
          "Ber": "\\mathcal{B}er"
          "Beta": "\\mathcal{B}eta"
          "Bin": "\\mathcal{B}in"
          "def": "\\stackrel{\\text{def}}{=}"
          "balpha": "\\boldsymbol\\alpha"
          "bbeta": "\\boldsymbol\\beta"
          "bdelta": "\\boldsymbol\\delta"
          "bmu": "\\boldsymbol\\mu"
          "bfeta": "\\boldsymbol\\eta"
          "btheta": "\\boldsymbol\\theta"
          "bpi": "\\boldsymbol\\pi"
          "bTheta": "\\boldsymbol\\Theta"
          "bSigma": "\\boldsymbol\\Sigma"
          "dev": "\\varepsilon"
          "bbr": "\\mathbb{R}"
          
          "ba": "\\mathbf{a}"
          "bb": "\\mathbf{b}"
          "bc": "\\mathbf{c}"
          "bd": "\\mathbf{d}"
          "be": "\\mathbf{e}"
          "bg": "\\mathbf{g}"
          "bu": "\\mathbf{u}"
          "bv": "\\mathbf{v}"
          "bw": "\\mathbf{w}"
          "bx": "\\mathbf{x}"
          "by": "\\mathbf{y}"
          "bz": "\\mathbf{z}"
          
          "bA": "\\mathbf{A}"
          "bB": "\\mathbf{B}"
          "bE": "\\mathbf{E}"
          "bD": "\\mathbf{D}"
          "bK": "\\mathbf{K}"
          "bS": "\\mathbf{S}"
          "bP": "\\mathbf{P}"
          "bQ": "\\mathbf{Q}"
          "bX": "\\mathbf{X}"
          "bY": "\\mathbf{Y}"
          "bZ": "\\mathbf{Z}"
          
          "calJ": "\\mathcal{J}"
          "calH": "\\mathcal{H}"
          "calN": "\\mathcal{N}"
          "calP": "\\mathcal{P}"
          "Jac": "\\operatorname{Jac}"
          "thetaMLE": "\\widehat{\\theta}_{\\text{MLE}}"
          "bthetaMLE": "\\widehat{\\btheta}_{\\text{MLE}}"
          "thetaMAP": "\\widehat{\\theta}_{\\text{MAP}}"
          "bthetaMAP": "\\widehat{\\btheta}_{\\text{MAP}}"
          "hattheta": "\\widehat{\\theta}"
          "hatbtheta": "\\widehat{\\btheta}"
          
# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jmyers7/stats-book-materials  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath